# ============================================================
# global_costmap.yaml — 全局代价地图参数
# ============================================================

global_costmap:
  global_costmap:
    ros__parameters:

      update_frequency: 2.0
      publish_frequency: 1.0

      global_frame: "map"
      robot_base_frame: "base_footprint"

      rolling_window: false
      resolution: 0.05

      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.5

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        enabled: true

      transform_tolerance: 0.5