# ============================================================
# local_costmap.yaml — 局部代价地图参数
# ============================================================

local_costmap:
  local_costmap:
    ros__parameters:

      update_frequency: 10.0
      publish_frequency: 5.0

      global_frame: "odom_combined"
      robot_base_frame: "base_footprint"

      rolling_window: true
      width: 5
      height: 5
      resolution: 0.05

      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.35

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        enabled: true

      publish_footprint: true
      transform_tolerance: 0.5